name: Build and push Docker image
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: "Set Job Environment Variables"
      run: |
        SHA7="${GITHUB_SHA::7}"
        DOCKER_TAG=$SHA7
        echo $DOCKER_TAG > docker-tag.txt
        echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV

    - name: Upload docker tag
      uses: actions/upload-artifact@v3
      with:
        name: docker-tag
        path: docker-tag.txt

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: "Build and Publish to DockerHub"
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: eeholmes/nmfsr
        username: eeholmes
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        workdir: ci
        platforms: linux/amd64,linux/arm64/v8,linux/arm64
        tags: "main, ${{env.DOCKER_TAG}}"

    - name: Export Full Conda Environment
      run: |
          docker run openscapes/rocker:main conda list --export
